import Navbar from "@/components/Navbar";
import "./globals.css";
import ReduxProviders from "@/provider/ReduxProviders";
import Auth from "@/utils/Auth";

export const metadata = {
  title: "react-portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProviders>
          <Auth>
            <Navbar />
            {children}
          </Auth>
        </ReduxProviders>
      </body>
    </html>
  );
}
